### ISSUE TITLE
Images seem too large and break the layout while page is loading

### ISSUE THREAD

**Issue by eralpkaraduman** [nicework-company/unhandledexception.club#11]
pre process them into smaller images, possibly by using;

https://www.gatsbyjs.com/plugins/gatsby-transformer-sharp/

**Comment by gkmngrgn** [comment]
@eralpkaraduman the ticket seems still open, is there anything that we forgot?

**Comment by eralpkaraduman** [comment]
> @eralpkaraduman the ticket seems still open, is there anything that we forgot?

nope, closing
