### ISSUE TITLE
Remove and gitignore .idea dir

### ISSUE THREAD

**Issue by eralpkaraduman** [nicework-company/unhandledexception.club#18]
Forgot to ignore this :/

- delete .idea folder from repo
- .gitignore it

**Comment by gkmngrgn** [comment]
@eralpkaraduman seems already done with this commit:
https://github.com/nicework-company/unhandledexception.club/commit/6eba348a754a4da0c3bf7a94bec71661c366d52c

**Comment by eralpkaraduman** [comment]
> @eralpkaraduman seems already done with this commit:
> 
> https://github.com/nicework-company/unhandledexception.club/commit/6eba348a754a4da0c3bf7a94bec71661c366d52c

right!
